
services:
  app:
    build: ./docker/php
    container_name: "${COMPOSE_PROJECT_NAME}_php"
    user: "${UID_GID:-1000:1000}" # ホストマシンと同じユーザー権限でコンテナ内のプロセスを実行
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    ports:
      - "9000:9000"
      - "5173:5173"
    environment:
      - APP_NAME=${APP_NAME:-Laravel}
      - APP_TIMEZONE=${APP_TIMEZONE:-Asia/Tokyo}
      - APP_LOCALE=${APP_LOCALE:-ja}
      - APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE:-ja}
      - APP_FAKER_LOCALE=${APP_FAKER_LOCALE:-ja_JP}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-database}
      - DB_USERNAME=${DB_USERNAME:-user}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
    networks:
      - php-nginx-net
  web:
    image: nginx:1.29.0-alpine
    container_name: "${COMPOSE_PROJECT_NAME}_nginx"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - php-nginx-net
  db:
    image: mysql:9.3
    container_name: "${COMPOSE_PROJECT_NAME}_mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    networks:
      - php-nginx-net
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME}_phpmyadmin"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${MYSQL_USER:-user}
      - PMA_PASSWORD=${MYSQL_PASSWORD:-secret}
      - TZ=Asia/Tokyo
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - php-nginx-net
  mailhog:
    image: mailhog/mailhog
    container_name: "${COMPOSE_PROJECT_NAME}_mail_server"
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - php-nginx-net
networks:
  php-nginx-net:
volumes:
  db_data: